### ISSUE TITLE
Regression introduced in v4.1.1 with InvalidCastException

### ISSUE THREAD

**Issue by vlm---** [agileobjects/ReadableExpressions#142]
Found another regression introduced in v4.1.1:

```csharp
using System;
using System.Linq.Expressions;
using AgileObjects.ReadableExpressions;

public class Program
{
	public static void Main()
	{
		Expression<Func<Product, bool>> exp = p => p.Id == 1 && p.Item is string;
		Console.WriteLine(exp.ToReadableString());
	}

	public class Product
	{
		public int Id { get; set; }
                public object Item { get; set; }
	}
}
```
```
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.TypeBinaryExpression' to type 'System.Linq.Expressions.UnaryExpression'.
   at AgileObjects.ReadableExpressions.Extensions.InternalExpressionExtensions.GetUnaryOperand(Expression unary)
   at AgileObjects.ReadableExpressions.Translations.BinaryTranslation.IsEnumType(Expression expression, Expression& enumExpression)
   at AgileObjects.ReadableExpressions.Translations.BinaryTranslation.TryGetEnumComparisonExpression(BinaryExpression comparison, Expression& leftOperand, Expression& rightOperand)
   at AgileObjects.ReadableExpressions.Translations.BinaryTranslation.For(BinaryExpression binary, ITranslationContext context)
   at AgileObjects.ReadableExpressions.Translations.ExpressionTranslation.GetDefaultTranslation(Expression expression)
   at AgileObjects.ReadableExpressions.Translations.ExpressionTranslation.GetTranslationFor(Expression expression)
   at AgileObjects.ReadableExpressions.Extensions.PublicTranslationContextExtensions.GetCodeBlockTranslationFor(ITranslationContext context, Expression expression)
   at AgileObjects.ReadableExpressions.Translations.LambdaTranslation..ctor(LambdaExpression lambda, ITranslationContext context)
   at AgileObjects.ReadableExpressions.Translations.ExpressionTranslation.GetDefaultTranslation(Expression expression)
   at AgileObjects.ReadableExpressions.Translations.ExpressionTranslation.GetTranslationFor(Expression expression)
   at AgileObjects.ReadableExpressions.Translations.ExpressionTranslation.GetTranslation()
   at AgileObjects.ReadableExpressions.ExpressionExtensions.ToReadableString(Expression expression, Func`2 configuration)
   at Program.<<Initialize>>d__0.MoveNext() in :line 10
--- End of stack trace from previous location ---
   at Program.<Main>()
```

Result with v4.1.0:
`p => (p.Id == 1) && (p.Item is string)`

**Comment by SteveWilkes** [comment]
Oh dear, another one! I've pushed v4.1.3 to NuGet with this fixed. Thanks for letting me know!
