### ISSUE TITLE
NetFramework xUnit test error

### ISSUE THREAD

**Issue by lbargaoanu** [agileobjects/ReadableExpressions#71]
```
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Windows.Forms.UnsafeNativeMethods.IWebBrowser2.get_RegisterAsDropTarget()
   at System.Windows.Forms.WebBrowser.set_AllowWebBrowserDrop(Boolean value)
   at AgileObjects.ReadableExpressions.Visualizers.Core.VisualizerDialog.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```
Fixed by restarting VS :)

**Comment by SteveWilkes** [comment]
I've seen this error before - it's [this one](https://stackoverflow.com/questions/27186913/unit-test-initialization-fails-with-webbrowser-control-comexception?rq=1), for example. If an error occurs opening the visualizer, its `WebBrowser` control gets itself into a broken state which is only fixed by closing and reopening Visual Studio.

I'm looking to rewrite the visualizers using WPF, which hopefully will see the back of these Winforms issues.

**Comment by lbargaoanu** [comment]
As long it can be worked around, no biggie :)
