### ISSUE TITLE
System.NotSupportedException in the newest Visual Studio

### ISSUE THREAD

**Issue by AradAral** [agileobjects/ReadableExpressions#81]
Hi there! Extremely useful extension!
I've been using it for quite a while now, but after I reinstalled Visual Studio 2019 (I'm on version 16.8.1 right now), whenever I click on the magnifier button, I get the following error window:
![image](https://user-images.githubusercontent.com/26527405/100415970-90585a80-3092-11eb-8e69-50412f25d7c9.png)

I was going to try uninstalling and then installing the extension again, but the "Uninstall" button is grayed out:
![image](https://user-images.githubusercontent.com/26527405/100416052-c72e7080-3092-11eb-8639-19004e39383f.png)

I'd appreciate any help.

**Comment by SteveWilkes** [comment]
Hello!

Thanks for letting me know about this - glad the extension has been useful!

Because it installs with an MSI, you have to uninstall it via Add/Remove Programs - could you give that a try and let me know how you get on?

Cheers!

Steve

**Comment by araxemy** [comment]
@SteveWilkes Hi, Steve. Thank you for the response!
I uninstalled it from Add/Remove Programs as you said (thanks for pointing that out by the way) and then installed it again. The problem however is still there.
One other thing I noticed is that this doesn't happen when I'm in a console app project, I try it in an ASP.NET Core project and I face this problem.

What do you think could be causing this?

**Comment by AradAral** [comment]
@SteveWilkes Hi, Steve. Thank you for the response!
I uninstalled it from Add/Remove Programs as you said (thanks for pointing that out by the way) and then installed it again. The problem however is still there.
One other thing I noticed is that this doesn't happen when I'm in a console app project, I try it in an ASP.NET Core project and I face this problem.

What do you think could be causing this?

**Comment by SteveWilkes** [comment]
Hmm - looks like we've run into [this .NET 5 breaking change](https://github.com/dotnet/runtime/issues/29976), which is causing issues [elsewhere](https://github.com/nhibernate/nhibernate-core/issues/2603), too.

I assume the VS debugger uses `BinaryFormatter` to serialize Expressions before sending them to the visualizer, and it's been disabled by default in ASP.NET Core 5, but not console apps. Does that match your setup?

You can enable it in Debug only using:

```xml
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <EnableUnsafeBinaryFormatterSerialization Condition=" '$(Configuration)' = 'Debug' ">
        true
    </EnableUnsafeBinaryFormatterSerialization>
</PropertyGroup>
```

There are [security considerations](https://docs.microsoft.com/en-gb/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete) to doing this, but I suspect unless you're using `BinaryFormatter` for serialization of objects from outside of your control, switching it on in Debug won't do any harm. No warranty intended or implied, of course!

Thanks again for bringing this to my attention, I'll have a look to see if there's anything I can do to work around it on my end, although I suspect it's down to how Visual Studio Debugger Visualizers are implemented, so it'll be one for Microsoft!

**Comment by SteveWilkes** [comment]
Hello! 

I've now had a reply on [Microsoft's Developer Community](https://developercommunity2.visualstudio.com/t/visual-studio-debugger-visualizers-and-binaryforma/1278642?from=email&viewtype=all#T-N1314383) regarding this, which confirms it's ASP.NET Core 5-specific, and is down to a change in Visual Studio.

The recommended fix is to enable the binary formatter in debug as described above.

Cheers,

Steve

**Comment by AradAral** [comment]
Hi! Sorry for being late!
Okay, got it, thank you!

**Comment by mhamri** [comment]
OMG!, this one should be on the readme.md. I'm installing and uninstalling things for two days, blamed my anti-virus and stuff BCS of this.

**Comment by SteveWilkes** [comment]
Sorry about that @mhamri - I've updated the readme as you suggested.

Al the best,

Steve

**Comment by drewnoakes** [comment]
Sounds like there's an issue with the installer too, if uninstall is not removing the visualizer from VS completely.

**Comment by SteveWilkes** [comment]
Thanks for the heads up on that one, @drewnoakes - I've added an answer to the SO question. The poster didn't actually run the uninstaller as far as I can tell, so I think it's probably fine.

**Comment by pantonis** [comment]
I added the ```EnableUnsafeBinaryFormatterSerialization ``` and I am getting the following error now:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Windows.Forms.UnsafeNativeMethods.IWebBrowser2.get_RegisterAsDropTarget()
   at System.Windows.Forms.WebBrowser.set_AllowWebBrowserDrop(Boolean value)
   at AgileObjects.ReadableExpressions.Visualizers.Dialog.Controls.VisualizerViewer.HandleShown(String translation)
   at AgileObjects.ReadableExpressions.Visualizers.Dialog.VisualizerDialog.<>c.<.ctor>b__8_0(Object sender, EventArgs args)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Microsoft.VisualStudio.Platform.AppDomainManager
    Assembly Version: 16.0.0.0
    Win32 Version: 16.0.30907.39
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.VisualStudio.Platform.AppDomainManager.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ClrCustomVisualizerVSHost
    Assembly Version: 16.0.0.0
    Win32 Version: 16.8.11214.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/ClrCustomVisualizerVSHost.DLL
----------------------------------------
Microsoft.VisualStudio.Debugger.Engine
    Assembly Version: 1.0.0.0
    Win32 Version: 16.8.11214.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/Microsoft.VisualStudio.Debugger.Engine.DLL
----------------------------------------
Microsoft.VisualStudio.DebuggerVisualizers
    Assembly Version: 16.0.0.0
    Win32 Version: 16.0.30618.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.DebuggerVisualizers.DLL
----------------------------------------
Microsoft.VisualStudio.Shell.15.0
    Assembly Version: 16.0.0.0
    Win32 Version: 16.0.30907.39
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.Shell.15.0.DLL
----------------------------------------
Microsoft.VisualStudio.OLE.Interop
    Assembly Version: 7.1.40304.0
    Win32 Version: 7.10.6070
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.OLE.Interop.DLL
----------------------------------------
Microsoft.VisualStudio.Shell.Interop
    Assembly Version: 7.1.40304.0
    Win32 Version: 7.10.6071
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.Shell.Interop.DLL
----------------------------------------
Microsoft.VisualStudio.Shell.Framework
    Assembly Version: 16.0.0.0
    Win32 Version: 16.8.30907.39
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.Shell.Framework.DLL
----------------------------------------
Microsoft.VisualStudio.Shell.Interop.8.0
    Assembly Version: 15.0.0.0
    Win32 Version: 8.0.50727.938 (QFE.050727-9300)
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Interop/Microsoft.VisualStudio.Shell.Interop.8.0.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
Microsoft.VisualStudio.Validation
    Assembly Version: 16.8.0.0
    Win32 Version: 16.8.21.42445
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.VisualStudio.Validation.DLL
----------------------------------------
Microsoft.VisualStudio.Threading
    Assembly Version: 16.8.0.0
    Win32 Version: 16.8.45.56235
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.Threading.16.0/Microsoft.VisualStudio.Threading.dll
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/System.Threading.Tasks.Extensions.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.20.12001
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
Microsoft.VisualStudio.Utilities
    Assembly Version: 16.0.0.0
    Win32 Version: 16.8.30907.39
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/Microsoft.VisualStudio.Utilities.DLL
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/System.Collections.Immutable.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/System.Memory.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/System.Numerics.Vectors.DLL
----------------------------------------
Microsoft.ServiceHub.Framework
    Assembly Version: 2.0.0.0
    Win32 Version: 2.7.100.16974
    CodeBase: file:///c:/program%20files%20(x86)/microsoft%20visual%20studio/2019/professional/common7/ide/commonextensions/microsoft/servicehubclient/Microsoft.ServiceHub.Framework.dll
----------------------------------------
System.IO.Pipelines
    Assembly Version: 4.0.2.1
    Win32 Version: 4.700.20.21406
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/System.IO.Pipelines.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Buffers/v4.0_4.0.3.0__cc7b13ffcd2ddd51/System.Buffers.dll
----------------------------------------
Nerdbank.Streams
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.78.14506
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Nerdbank.Streams.2.x/Nerdbank.Streams.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.2
    Win32 Version: 12.0.2.23317
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.12.0.0.2/Newtonsoft.Json.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
StreamJsonRpc
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.114.35280
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/StreamJsonRpc.2.x/StreamJsonRpc.dll
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 1.0.0.0
    Win32 Version: 4.700.20.21406
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
MessagePack
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.194.40517
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/MessagePack.2.x/MessagePack.dll
----------------------------------------
MessagePack.Annotations
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.194.40517
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/MessagePack.2.x/MessagePack.Annotations.dll
----------------------------------------
Microsoft.VisualStudio.RpcContracts
    Assembly Version: 16.8.30.0
    Win32 Version: 16.8.30.18716
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.VisualStudio.RpcContracts.dll
----------------------------------------
Microsoft.VisualStudio.Telemetry
    Assembly Version: 16.0.0.0
    Win32 Version: 16.3.76.18156
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.VisualStudio.Telemetry.DLL
----------------------------------------
Microsoft.VisualStudio.Utilities.Internal
    Assembly Version: 14.0.0.0
    Win32 Version: 16.3.5.21611
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.VisualStudio.Utilities.Internal.DLL
----------------------------------------
Microsoft.VisualStudio.RemoteControl
    Assembly Version: 14.0.0.0
    Win32 Version: 16.3.19.64848
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.VisualStudio.RemoteControl.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.Diagnostics.Tracing.EventSource
    Assembly Version: 1.1.28.0
    Win32 Version: 1.1.28.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.Diagnostics.Tracing.EventSource.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.ServiceHub.Client
    Assembly Version: 2.0.0.0
    Win32 Version: 2.7.100.16974
    CodeBase: file:///c:/program%20files%20(x86)/microsoft%20visual%20studio/2019/professional/common7/ide/commonextensions/microsoft/servicehubclient/Microsoft.ServiceHub.Client.dll
----------------------------------------
Microsoft.ServiceHub.Resources
    Assembly Version: 2.0.0.0
    Win32 Version: 2.7.100.16974
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.ServiceHub.Resources.DLL
----------------------------------------
System.Threading.Tasks.Dataflow
    Assembly Version: 4.6.5.0
    Win32 Version: 4.700.20.21406
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/System.Threading.Tasks.Dataflow.DLL
----------------------------------------
Microsoft.VisualStudio.GraphModel
    Assembly Version: 16.0.0.0
    Win32 Version: 16.8.30607.65
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.GraphModel.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Microsoft.VisualStudio.Shell.Interop.9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1 built by: SP
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.Shell.Interop.9.0.DLL
----------------------------------------
Microsoft.VisualStudio.Imaging
    Assembly Version: 16.0.0.0
    Win32 Version: 16.8.30907.39
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/Microsoft.VisualStudio.Imaging.DLL
----------------------------------------
Microsoft.VisualStudio.Diagnostics.Assert
    Assembly Version: 16.0.0.0
    Win32 Version: 16.0.30907.39
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Microsoft.VisualStudio.Diagnostics.Assert.DLL
----------------------------------------
System.Design
    Assembly Version: 16.0.0.0
    Win32 Version: 16.6.30319.200 built by: D16.8
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PrivateAssemblies/System.Design.DLL
----------------------------------------
EnvDTE
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.932 (QFE.050727-9300)
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/EnvDTE.DLL
----------------------------------------
Microsoft.VisualStudio.ComponentModelHost
    Assembly Version: 16.0.0.0
    Win32 Version: 16.8.239.35654
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.ComponentModelHost.DLL
----------------------------------------
Microsoft.VisualStudio.TextManager.Interop
    Assembly Version: 7.1.40304.0
    Win32 Version: 7.10.6070
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.TextManager.Interop.DLL
----------------------------------------
Microsoft.VisualStudio.Text.Data
    Assembly Version: 16.0.0.0
    Win32 Version: 16.8.239.35654
    CodeBase: file:///c:/program%20files%20(x86)/microsoft%20visual%20studio/2019/professional/common7/ide/commonextensions/microsoft/editor/Microsoft.VisualStudio.Text.Data.dll
----------------------------------------
Microsoft.VisualStudio.VSHelp
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.00.9466
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/IDE/PublicAssemblies/Microsoft.VisualStudio.VSHelp.DLL
----------------------------------------
AgileObjects.ReadableExpressions.Visualizers.Vs16
    Assembly Version: 3.3.1.0
    Win32 Version: 3.3.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/Professional/Common7/Packages/Debugger/Visualizers/AgileObjects.ReadableExpressions.Visualizers.Vs16.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by SteveWilkes** [comment]
I've seen that sort of error happen @pantonis - if something goes wrong with the debugger (which can be the visualizers, and can be the way the visualizers handle the debugger in particular states - it's weird and difficult to diagnose), it can throw those errors until you close + reopen Visual studio.
